feat (actions):
Added PAT validation.

diff --git a/.github/workflows/build_and_release.yml b/.github/workflows/build_and_release.yml
--- a/.github/workflows/build_and_release.yml
+++ b/.github/workflows/build_and_release.yml
@@ -7,8 +7,33 @@ on:
       - pre_release
 
 jobs:
+  validate_tokens:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check VSCE_PUBLISH_PAT validity
+        run: |
+          echo "Checking VSCE_PUBLISH_PAT..."
+          if ! vsce ls-publishers -p ${{ secrets.VSCE_PUBLISH_PAT }}; then
+            echo "VSCE_PUBLISH_PAT is invalid or expired."
+            exit 1
+          else
+            echo "VSCE_PUBLISH_PAT is valid."
+          fi
+
+      - name: Check PERSONAL_ACCESS_TOKEN validity
+        run: |
+          echo "Checking PERSONAL_ACCESS_TOKEN..."
+          response=$(curl -s -o /dev/null -w "%{http_code}" -H "Authorization: token ${{ secrets.PERSONAL_ACCESS_TOKEN }}" https://api.github.com/user)
+          if [ "$response" -ne 200 ]; then
+            echo "PERSONAL_ACCESS_TOKEN is invalid or expired."
+            exit 1
+          else
+            echo "PERSONAL_ACCESS_TOKEN is valid."
+          fi
+
   build_and_release:
     runs-on: ubuntu-latest
+    needs  : validate_tokens
     if     : github.event.head_commit.author.email != 'github-actions[bot]@users.noreply.github.com'
     outputs: 
       isPrerelease: ${{ steps.set_prerelease.outputs.isPrerelease }}
